export const RoomList = [
  {
    id: 'restaurant',
    label: '식당',
    floor: 'b1',
    maxCapacity: 10,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '101room',
    label: '101호',
    floor: '1f',
    maxCapacity: 2,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '102room',
    label: '102호',
    floor: '1f',
    maxCapacity: 4,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '103room',
    label: '103호',
    floor: '1f',
    maxCapacity: 3,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '104room',
    label: '104호',
    floor: '1f',
    maxCapacity: 5,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '105room',
    label: '105호',
    floor: '1f',
    maxCapacity: 10,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '106room',
    label: '106호',
    floor: '1f',
    maxCapacity: 5,
    currentApplicants: 2,
    isOndol: true,
  },
  {
    id: '107room',
    label: '107호',
    floor: '1f',
    maxCapacity: 5,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '301room',
    label: '301호',
    floor: '3f',
    maxCapacity: 2,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '302room',
    label: '302호',
    floor: '3f',
    maxCapacity: 3,
    currentApplicants: 1,
    isOndol: false,
  },
  {
    id: '303room',
    label: '303호',
    floor: '3f',
    maxCapacity: 4,
    currentApplicants: 3,
    isOndol: false,
  },
  {
    id: '304room',
    label: '304호',
    floor: '3f',
    maxCapacity: 6,
    currentApplicants: 2,
    isOndol: false,
  },
  {
    id: '305room',
    label: '305호',
    floor: '3f',
    maxCapacity: 6,
    currentApplicants: 1,
    isOndol: false,
  },
  {
    id: '306room',
    label: '306호',
    floor: '3f',
    maxCapacity: 8,
    currentApplicants: 5,
    isOndol: true,
  },
  {
    id: '307room',
    label: '307호',
    floor: '3f',
    maxCapacity: 4,
    currentApplicants: 2,
    isOndol: true,
  },
]
